# Generated by Django 6.0.1 on 2026-01-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prompt',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='data',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='exercise',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instruction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('READ', 'O‘qish'), ('WRITE', 'Yozish'), ('LISTEN', 'Tinglab tanlash'), ('QUIZ', 'Test')], max_length=10),
        ),
    ]
