# Generated by Django 6.0.1 on 2026-01-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0003_achievement_vocabularycategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arabic_text', models.CharField(max_length=120)),
                ('transliteration', models.CharField(blank=True, max_length=120)),
                ('translation_uz', models.CharField(blank=True, max_length=200)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/letter_examples/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level', 'id']},
        ),
        migrations.AlterModelOptions(
            name='diacritic',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['arabic']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lessonsection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userwordprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('READ', 'O‘qish'), ('WRITE', 'Yozish'), ('LISTEN', 'Tinglab tanlash'), ('QUIZ', 'Test'), ('COMBO', 'Harf + harakat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='related_diacritics',
            field=models.ManyToManyField(blank=True, related_name='grammar_rules', to='arab.diacritic'),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/letters/'),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='arab.achievement'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstreak',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordexample',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/word_examples/'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['arabic'], name='arab_word_arabic_a5315b_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='uniq_lesson_order_in_unit'),
        ),
        migrations.AddConstraint(
            model_name='lessonsection',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='uniq_section_order_in_lesson'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_unit_order_in_course'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='uniq_user_achievement'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('word__isnull', False), ('letter__isnull', True)), models.Q(('word__isnull', True), ('letter__isnull', False)), _connector='OR'), name='usercard_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='uniq_user_word_card'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(fields=('user', 'letter'), name='uniq_user_letter_card'),
        ),
        migrations.AddConstraint(
            model_name='userlessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson_progress'),
        ),
        migrations.AddConstraint(
            model_name='userwordprogress',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='uniq_user_word_progress'),
        ),
        migrations.AddField(
            model_name='letterexample',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='arab.letter'),
        ),
    ]
