# Generated by Django 6.0.1 on 2026-01-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0005_tajweedrule_tajweedtag_tajweedexample_tajweedmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tajweedexample',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tajweedrule',
            options={'ordering': ['level', 'title']},
        ),
        migrations.AlterModelOptions(
            name='tajweedtag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='tajweedexample',
            name='highlight_spans',
        ),
        migrations.AddField(
            model_name='tajweedmark',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
