# Generated by Django 6.0.1 on 2026-01-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0006_alter_tajweedexample_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tajweedexample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tajweedtag',
            options={},
        ),
    ]
