# Generated by Django 6.0.1 on 2026-01-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0008_tajweedquiz_tajweedquizoption_tajweedquizattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tajweedquizattempt',
            name='arab_tajwee_user_id_fd5afe_idx',
        ),

        # ✅ correct_rule — DEFAULT YO‘Q, NULL=True
        migrations.AddField(
            model_name='tajweedquizattempt',
            name='correct_rule',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attempts_correct_rule',
                to='arab.tajweedrule',
            ),
        ),

        # ✅ example — DEFAULT YO‘Q, NULL=True
        migrations.AddField(
            model_name='tajweedquizattempt',
            name='example',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attempts',
                to='arab.tajweedexample',
            ),
        ),

        migrations.AddField(
            model_name='tajweedquizattempt',
            name='selected_rule',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attempts_selected_rule',
                to='arab.tajweedrule',
            ),
        ),

        migrations.AddIndex(
            model_name='tajweedquizattempt',
            index=models.Index(fields=['user', 'created_at'], name='arab_tajwee_user_id_d7a3f8_idx'),
        ),

        migrations.AddIndex(
            model_name='tajweedquizattempt',
            index=models.Index(fields=['correct_rule', 'is_correct'], name='arab_tajwee_correct_e5e888_idx'),
        ),

        migrations.RemoveField(
            model_name='tajweedquizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='tajweedquizattempt',
            name='selected_option',
        ),
    ]
