# Generated by Django 6.0.1 on 2026-01-19 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0009_remove_tajweedquizattempt_arab_tajwee_user_id_fd5afe_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TajweedProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tajweedmark',
            options={'ordering': ['start', 'end']},
        ),
        migrations.RemoveIndex(
            model_name='tajweedquizattempt',
            name='arab_tajwee_user_id_155c35_idx',
        ),
        migrations.RemoveIndex(
            model_name='tajweedquizattempt',
            name='arab_tajwee_user_id_d7a3f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='tajweedquizattempt',
            name='arab_tajwee_correct_e5e888_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tajweedmark',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tajweedmark',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='arab.tajweedrule'),
        ),
        migrations.AlterField(
            model_name='tajweedmark',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to='arab.tajweedtag'),
        ),
        migrations.AlterField(
            model_name='tajweedmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tajweed_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tajweedquizattempt',
            name='correct_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts_correct_rule', to='arab.tajweedrule'),
        ),
        migrations.AlterField(
            model_name='tajweedquizattempt',
            name='example',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='arab.tajweedexample'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tajweedmark',
            index=models.Index(fields=['example', 'start', 'end'], name='arab_tajwee_example_b47ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='tajweedmark',
            index=models.Index(fields=['rule'], name='arab_tajwee_rule_id_b02583_idx'),
        ),
        migrations.AddIndex(
            model_name='tajweedmark',
            index=models.Index(fields=['tag'], name='arab_tajwee_tag_id_5bd9db_idx'),
        ),
        migrations.AddField(
            model_name='tajweedprogress',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arab.tajweedrule'),
        ),
        migrations.AddField(
            model_name='tajweedprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tajweedmark',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tajweedmark',
            name='score',
        ),
        migrations.AddConstraint(
            model_name='tajweedprogress',
            constraint=models.UniqueConstraint(fields=('user', 'rule'), name='uniq_user_rule_progress'),
        ),
    ]
