# Generated by Django 6.0 on 2026-01-20 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0012_usergamification_userdailystat_userweakarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamification',
            name='hearts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usergamification',
            name='last_heart_refill',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
