# Generated by Django 6.0 on 2026-01-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0013_usergamification_hearts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/questions/'),
        ),
    ]
