# Generated by Django 6.0 on 2026-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0014_question_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamification',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
