# Generated by Django 6.0 on 2026-01-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0015_usergamification_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='tajweedexample',
            name='description',
            field=models.TextField(blank=True, help_text="Qoida qanday qo'llanilishi haqida izoh"),
        ),
        migrations.AddField(
            model_name='tajweedexample',
            name='transliteration',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
