# Generated by Django 6.0 on 2026-01-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0016_tajweedexample_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('file', 'File (MP4)')], default='youtube', max_length=10)),
                ('video_id', models.CharField(blank=True, help_text='YouTube ID', max_length=50)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Sekundlarda')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='arab.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('is_watched', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='arab.lessonvideo')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
