# Generated by Django 6.0 on 2026-01-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0017_lessonvideo_uservideoprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='lessonvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text="To'g'ridan-to'g'ri video URL (MP4, yoki boshqa)", max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='provider',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('url', 'Direct URL (MP4/Video link)')], default='youtube', max_length=10),
        ),
    ]
