# Generated by Django 6.0 on 2026-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0018_remove_lessonvideo_video_file_lessonvideo_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tajweedrule',
            name='category',
            field=models.CharField(choices=[('alphabet', 'Harflar va Maxraj'), ('noon_sakinah', 'Noon Sakinah va Tanween'), ('meem_sakinah', 'Meem Sakinah'), ('mudood', "Muddood (Cho'ziqlar)"), ('sifat', 'Harf Sifatlari'), ('other', 'Boshqa qoidalar')], default='other', max_length=50),
        ),
    ]
