# Generated by Django 6.0 on 2026-01-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0020_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSurah',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('ayah_count', models.PositiveIntegerField()),
                ('place', models.CharField(choices=[('Mecca', 'Mecca'), ('Medina', 'Medina')], default='Mecca', max_length=20)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='QuranAyah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_surah', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/quran/')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='arab.quransurah')),
            ],
            options={
                'ordering': ['surah', 'number_in_surah'],
                'unique_together': {('surah', 'number_in_surah')},
            },
        ),
    ]
