# Generated by Django 6.0 on 2026-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0022_mission_usermissionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='JSON list of face encoding values', null=True),
        ),
    ]
