# Generated by Django 6.0 on 2026-01-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0023_profile_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='face_encoding',
        ),
    ]
