# Generated by Django 6.0 on 2026-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0024_remove_profile_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='makhraj_description',
            field=models.TextField(blank=True, help_text='Description of articulation mechanism'),
        ),
        migrations.AddField(
            model_name='letter',
            name='makhraj_image',
            field=models.ImageField(blank=True, help_text='Image showing articulation point', null=True, upload_to='makhraj/'),
        ),
    ]
