# Generated by Django 6.0.1 on 2026-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0025_letter_makhraj_description_letter_makhraj_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='makhraj',
            field=models.TextField(blank=True, help_text="Talaffuz o'rni (maxraj)"),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(blank=True, help_text="O'qilishi (O'zbek lofida)", max_length=200),
        ),
    ]
