# Generated by Django 6.0 on 2026-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0026_word_makhraj_word_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_type',
            field=models.CharField(blank=True, help_text="So'z turkumi (Ot, Sifat, va h.k.)", max_length=50),
        ),
    ]
