# Generated by Django 6.0 on 2026-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0028_course_image_profile_current_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='svg_path',
            field=models.TextField(blank=True, help_text='SVG d atributi (stroke animatsiyasi uchun)'),
        ),
        migrations.AddField(
            model_name='letter',
            name='viewbox',
            field=models.CharField(default='0 0 100 100', help_text="SVG viewbox o'lchami", max_length=50),
        ),
    ]
