# Generated by Django 6.0 on 2026-01-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0029_letter_svg_path_letter_viewbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/placement/')),
                ('level_tag', models.CharField(default='A0', max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='usercard',
            name='uniq_user_word_card',
        ),
        migrations.RemoveConstraint(
            model_name='usercard',
            name='uniq_user_letter_card',
        ),
        migrations.AddField(
            model_name='lesson',
            name='blocks',
            field=models.JSONField(blank=True, default=list, help_text='Lesson mini-bloklar ketma-ketligi'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(condition=models.Q(('word__isnull', False)), fields=('user', 'word'), name='uniq_user_word_card'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(condition=models.Q(('letter__isnull', False)), fields=('user', 'letter'), name='uniq_user_letter_card'),
        ),
        migrations.AddField(
            model_name='placementoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='arab.placementquestion'),
        ),
    ]
