# Generated by Django 6.0 on 2026-01-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0030_placementoption_placementquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scenarios/')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fas fa-comments', help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Scenario Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='DialogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(help_text='Character name (e.g. Ahmad, Seller)', max_length=100)),
                ('text_arabic', models.TextField()),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField(blank=True)),
                ('transliteration', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/dialogs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_user_line', models.BooleanField(default=False, help_text='Should the user answer this?')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_lines', to='arab.scenario')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='arab.scenariocategory'),
        ),
        migrations.CreateModel(
            name='PhrasebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_arabic', models.CharField(max_length=255)),
                ('text_uz', models.CharField(max_length=255)),
                ('text_ru', models.CharField(blank=True, max_length=255)),
                ('transliteration', models.CharField(blank=True, max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/phrases/')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrases', to='arab.scenario')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrases', to='arab.scenariocategory')),
            ],
            options={
                'verbose_name_plural': 'Phrasebook Entries',
            },
        ),
    ]
