# Generated by Django 6.0 on 2026-01-26 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0031_scenario_scenariocategory_mission_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('quest_type', models.CharField(choices=[('XP', 'Gain XP'), ('LESSON', 'Complete Lessons'), ('REVIEW', 'Review Cards'), ('PERFECT', 'Perfect Lesson (No mistakes)')], max_length=20)),
                ('target_amount', models.PositiveIntegerField(default=1)),
                ('reward_xp', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='usergamification',
            name='current_league',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('EMERALD', 'Emerald'), ('DIAMOND', 'Diamond')], default='BRONZE', max_length=20),
        ),
        migrations.AddField(
            model_name='usergamification',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergamification',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergamification',
            name='league_xp',
            field=models.PositiveIntegerField(default=0, help_text='Weekly XP for league ranking'),
        ),
        migrations.AddField(
            model_name='usergamification',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usergamification',
            name='streak_freeze_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arab.dailyquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quest', 'day')},
            },
        ),
    ]
