# Generated by Django 6.0 on 2026-01-27 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0032_dailyquest_usergamification_current_league_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_time', models.TimeField(blank=True, help_text='Daily reminder time', null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='User notes / eslatmalar')),
                ('push_subscription', models.JSONField(blank=True, help_text='Browser push subscription data', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
