# Generated by Django 6.0 on 2026-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0034_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='arabic',
            field=models.CharField(error_messages={'unique': "Bu so'z allaqachon mavjud!"}, max_length=100, unique=True),
        ),
    ]
