# Generated by Django 6.0 on 2026-01-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0035_word_difficulty_alter_word_arabic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_taken_placement_test',
            field=models.BooleanField(default=False, help_text='Whether user has completed placement test'),
        ),
    ]
