# Generated by Django 6.0 on 2026-02-02 20:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0037_arabicroot_nahvsentence_sentenceexercise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Instructions for the user')),
                ('level', models.CharField(choices=[('A0', 'A0 (Introduction)'), ('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)')], default='A0', max_length=10)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('deadline', models.DateTimeField(help_text='Submission deadline')),
                ('is_published', models.BooleanField(default=False)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='arab.course')),
            ],
            options={
                'verbose_name': 'Uyga vazifa',
                'verbose_name_plural': 'Uyga vazifalar',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_submissions/')),
                ('text_content', models.TextField(blank=True, help_text='Optional text submission')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('submitted', 'Topshirildi (Tekshirilmoqda)'), ('graded', 'Tekshirildi (Baho olingan)'), ('rejected', 'Rad etildi (Qayta topshirish kerak)')], default='submitted', max_length=20)),
                ('admin_feedback', models.TextField(blank=True, help_text="Teacher's feedback")),
                ('score', models.PositiveIntegerField(blank=True, help_text='XP awarded', null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='arab.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vazifa javobi',
                'verbose_name_plural': 'Vazifa javoblari',
                'ordering': ['-submitted_at'],
                'unique_together': {('homework', 'user')},
            },
        ),
    ]
