# Generated by Django 6.0 on 2026-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0038_homework_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='audio_source',
            field=models.CharField(default='auto', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='source_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='word',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='wazn',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
