# Generated by Django 6.0 on 2026-02-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arab', '0038_homework_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, help_text='Attachment for users', null=True, upload_to='homework_files/'),
        ),
    ]
